<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Failed suite [SmokeTestSuites]" duration-ms="10359" started-at="2018-04-02T10:43:40Z" finished-at="2018-04-02T10:43:50Z">
    <groups>
    </groups>
    <test name="Test(failed)" duration-ms="10359" started-at="2018-04-02T10:43:40Z" finished-at="2018-04-02T10:43:50Z">
      <class name="DataDrivenFramework.LoginFail">
        <test-method status="FAIL" signature="Home(java.lang.String, java.lang.String)[pri:0, instance:DataDrivenFramework.LoginFail@6f7fd0e6]" name="Home" duration-ms="8764" started-at="2018-04-02T16:13:40Z" data-provider="testdataprovider" finished-at="2018-04-02T16:13:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at DataDrivenFramework.LoginFail.Home(LoginFail.java:37)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:497)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Home -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:DataDrivenFramework.LoginFail@6f7fd0e6]" name="tearDown" is-config="true" duration-ms="1239" started-at="2018-04-02T16:13:49Z" finished-at="2018-04-02T16:13:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Home status=FAILURE method=LoginFail.Home(java.lang.String, java.lang.String)[pri:0, instance:DataDrivenFramework.LoginFail@6f7fd0e6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- DataDrivenFramework.LoginFail -->
    </test> <!-- Test(failed) -->
  </suite> <!-- Failed suite [SmokeTestSuites] -->
</testng-results>
